####
# Build image
####
FROM --platform=linux/arm64 container-registry.oracle.com/graalvm/jdk:21 AS build
LABEL maintainer=avvero

COPY gradlew /app/
COPY gradle /app/gradle
WORKDIR /app
RUN ./gradlew --version

WORKDIR /app
COPY . .
RUN ./gradlew emk-application:nativeCompile --no-daemon

####
# Runtime image
####
FROM debian:sid-slim
LABEL maintainer=avvero

COPY --from=build /app/emk-application/build/native/nativeCompile/emk-application /app/emk-application

EXPOSE 8080 9093 2181

CMD [ "/app/emk-application" ]