####
# Build image
####
FROM --platform=linux/arm64 ghcr.io/graalvm/graalvm-ce:ol9-java17 AS build
LABEL maintainer avvero

WORKDIR /app
COPY . .
RUN ./gradlew nativeCompile

####
# Runtime image
####
FROM debian:sid-slim
LABEL maintainer avvero

COPY --from=build /app/build/native/nativeCompile/embedded-kafka /app/embedded-kafka

EXPOSE 8080
EXPOSE 9093
EXPOSE 2181

ENTRYPOINT [ "/app/embedded-kafka" ]